# Example config for apigee-remote-service-envoy in SaaS.
# You must update the tenant values appropriately.
tenant:
  management_api: https://istioservices.apigee.net/edgemicro
  remote_service_api: https://theganyo1-eval-test.apigee.net/istio-auth
  org_name: theganyo1-eval
  env_name: test
  key: NotReal
  secret: NotReal
products:
  refresh_rate: 2m
analytics:
  file_limit: 1024
  collection_interval: 10s
auth:
  api_key_cache_duration: 30m
  api_key_claim:
