# Example SaaS Config
tenant:
  management_api: https://ORG-ENV.apigee.net/istio-auth
  remote_service_api: https://ORG-ENV.apigee.net/istio-auth
  org_name: ORG
  env_name: ENV
  key: KEY
  secret: SECRET
