builds:
  - main: main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - format: tar.gz
    replacements:
      darwin: macOS
      amd64: 64-bit
    files:
      - LICENSE
      - README.md
      - samples/**/*
release:
  draft: true
  prerelease: true
