# Example ConfigMap for apigee-remote-service-envoy configuration in SaaS.
# You must update the tenant values appropriately.
# Note: Alternatively, you can use the generated config from the CLI directly.
#       Direct the output to `config.yaml` and run the follow command on it:
#       `kubectl -n apigee create configmap apigee-remote-service-envoy --from-file=config.yaml`
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigee-remote-service-envoy
  namespace: apigee
data:
  config.yaml: |
    tenant:
      management_api: https://istioservices.apigee.net/edgemicro
      remote_service_api: https://theganyo1-eval-test.apigee.net/istio-auth
      org_name: theganyo1-eval
      env_name: test
      key: NotReal
      secret: NotReal
    products:
      refresh_rate: 2m
    analytics:
      file_limit: 1024
      collection_interval: 10s
    auth:
      api_key_cache_duration: 30m
      api_key_claim:
