name: Build

on:
  push:
  pull_request:
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v1
      - 
        name: Reviewdog Lint
        uses: reviewdog/action-golangci-lint@v1
          
  test:
    name: Test and Cover
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v1
      - 
        name: Run Unit tests
        run: go test -coverprofile=coverage.txt ./...
      - 
        name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v1
      -
        name: Build and Push Docker image
        uses: docker/build-push-action@v1
        with:
          repository: apigee-api-management-istio/apigee-remote-service-envoy
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          registry: gcr.io
          tag_with_ref: true
          add_git_labels: true
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and Push Docker image for debugging
        uses: docker/build-push-action@v1
        with:
          repository: apigee-api-management-istio/apigee-remote-service-envoy-debug
          dockerfile: Dockerfile_debug
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          registry: gcr.io
          tag_with_ref: true
          add_git_labels: true
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
